[package]
name = "game"
version = "0.2.9"
edition = "2021"

[workspace]
members = ["launchers/wasm", "launchers/native"]

[profile.dev]
opt-level = 1

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true

[workspace.dependencies]
bevy = "0.10.1"

[features]
default = []
inspect = ["bevy/bevy_dylib", "bevy-inspector-egui", "bevy_mod_picking/debug"]

[dependencies]
bevy.workspace = true
rand = "0.8"
lazy_static = "1.4.0"
bevy_sprite3d = "2.4.0"
bevy-inspector-egui = { version = "0.18.3", optional = true }
bevy_mod_picking = { version = "0.13.0", default-features = false, features = [
    "selection",
    "backend_raycast",
    # "backend_egui",
] }
bevy_tweening = { version = "0.7.0", default-features = false, features = [
    "bevy_text",
] }

[patch.crates-io]
bevy_tweening = { git = "https://github.com/sibsibsib/bevy_tweening", branch = "mirrored_repeat_fix" }
