[package]
name = "game"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["launchers/wasm", "launchers/native"]

[profile.dev]
opt-level = 1

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true

[workspace.dependencies]
bevy = "0.10.1"

[features]
default = []
inspect = ["bevy-inspector-egui"]

[dependencies]
bevy.workspace = true
bevy-inspector-egui = { version = "0.18.3", optional = true }
bevy_tweening = { version = "0.7.0", default-features = false, features = [
    "bevy_text",
] }
lazy_static = "1.4.0"

[patch.crates-io]
bevy_tweening = { git = "https://github.com/sibsibsib/bevy_tweening", branch = "mirrored_repeat_fix" }
