[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[config]
default_to_workspace = true

[tasks.default]
alias = "check"

[tasks.docs]
description = "Generate docs"
command = "cargo"
args = ["doc", "--all"]

[tasks.upload-docs]
description = "Upload docs"
command = "cargo"
args = ["doc-upload"]

[tasks.clean]
description = "Clean all target directory"
command = "cargo"
args = ["clean"]

[tasks.fmt]
description = "Check format quality"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.fix-fmt]
description = "Fix format"
command = "cargo"
args = ["fmt", "--all"]

[tasks.clippy]
description = "Check code quality"
env_files = [".env.dev"]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.fix-clippy]
description = "Fix code quality"
env_files = [".env.dev"]
command = "cargo"
args = ["fix", "--allow-dirty"]

[tasks.test]
description = "Check all unit test"
env_files = [".env.dev"]
command = "cargo"
args = ["test"]
dependencies = ["fmt", "clippy"]

[tasks.check]
description = "Check all issues, format and code quality"
dependencies = ["fmt", "clippy", "test"]

[tasks.fix-all]
description = "Try fix all clippy and format issues"
dependencies = ["fix-fmt", "fix-clippy"]

[tasks.build]
description = "Generate release binary/lib"
dependencies = [
    "fmt",
    "clippy",
    "test",
    "release-native",
    "release-web",
]

[tasks.dev]
alias = "run-native"

