[package]
name = "native_kill_errors"
version = "0.2.0"
edition = "2021"
workspace = "../.."

[features]
default = []
inspect = ["game/inspect"]

[dependencies]
bevy.workspace = true
game = { path = "../.." }
open = "4.1.0"
