[tasks.run-native]
env_files = ["../../.env"]
command = "mold"
args = ["-run", "cargo", "run", "--features", "inspect"]
watch.watch = [
    "../../src",
    "../../assets",
    "../../Cargo.toml",
    "assets",
    "src",
    "Cargo.toml",
]

[tasks.release-native]
env_files = ["../../.env"]
command = "mold"
args = ["-run", "cargo", "build", "--release"]
