name: Upload to itch io

on:
  workflow_call:
    inputs:
      author:
        required: true
        type: string
      file_name:
        required: true
        type: string
      name:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Set Version
        run: |
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      # Upload To Itch.io
      - uses: SergioRibera/itchio-upload-action@main
        with:
          api-key: ${{ secrets.BUTLER_CREDENTIALS }}
          channel: ${{ inputs.os }}
          path: ${{ inputs.file_name }}
          project: ${{ inputs.author }}/${{ inputs.name }}
          version: ${{ env.version }}
