name: Release WASM (GitHub Pages)

permissions:
  contents: write

on:
  push:
    paths-ignore:
      - ".github/build.yml"
      - ".github/release-*.yml"
      - "**/Makefile.toml"
      - "README.md"
    tags:
      - "*"

env:
  APP_NAME: kill_errors
  PUBLIC_URL: /game_kill_errors/

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - name: Setup | Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: "latest"
      - name: Setup target
        run: rustup target add wasm32-unknown-unknown
      - name: Build | Trunk
        run: |
          cd launchers/wasm
          trunk build --release --public-url ${{ env.PUBLIC_URL }}

      - name: Post Build | Upload dist
        uses: actions/upload-artifact@v3
        with:
          path: ./launchers/wasm/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      APP_NAME: ${{env.APP_NAME}}
    steps:
      - name: Setup | Download dist
        uses: actions/download-artifact@v3

      - name: Setup | Place dist
        run: |
          mv ./artifact ./dist
          tar cvzf ${{env.APP_NAME}}-wasm32-unknown-unknown.tar.gz dist/* dist/assets
          zip -r ${{env.APP_NAME}}-wasm32-unknown-unknown.zip dist/* dist/assets

      - name: Deploy | Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/

      - name: Release | Upload
        uses: softprops/action-gh-release@v1
        with:
          files: ${{env.APP_NAME}}-wasm32-unknown-unknown.tar.gz
          prerelease: ${{ contains(github.ref_name, 'a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-itch:
    needs: deploy
    uses: ./.github/workflows/itch.yml
    with:
      author: sergioribera
      file_name: ${{ needs.deploy.outputs.APP_NAME }}-wasm32-unknown-unknown.zip
      name: ${{ env.APP_NAME }}
      os: html5
