name: Release WASM (GitHub Pages)

permissions:
  contents: write

on:
  push:
    paths-ignore:
      - ".github/build.yml"
      - ".github/release-*.yml"
      - "**/Makefile.toml"
      - "README.md"
    tags:
      - "*"

env:
  PUBLIC_URL: /wasm-kill-errors/

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checks
        uses: ./github/workflows/ci.yml

  build:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Load .env file
        uses: xom9ikk/dotenv@v2

      - name: Setup | Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: "latest"

      - name: Build | Trunk
        run: |
          cd launchers/wasm
          trunk build --release --public-url ${{ env.PUBLIC_URL }}

      - name: Post Build | Upload dist
        uses: actions/upload-artifact@v3
        with:
          path: ./launchers/wasm/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Download dist
        uses: actions/download-artifact@v3

      - name: Setup | Place dist
        run: mv ./artifact ./dist && tar cvzf wasm-kill-errors.tar.gz dist

      - name: Deploy | Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/
